# Generated by Django 2.1.1 on 2018-09-16 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='BlogCategory',
        ),
    ]
